package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.dartnative.DartNativeAndroidPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_android, com.dartnative.DartNativeAndroidPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.audio.DartNativeAudioPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_audio, com.dartnative.audio.DartNativeAudioPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.camera.DartNativeCameraPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_camera, com.dartnative.camera.DartNativeCameraPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.compressor.DartNativeCompressorPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_compressor, com.dartnative.compressor.DartNativeCompressorPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.imagecrop.DartNativeImageCropPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_image_crop, com.dartnative.imagecrop.DartNativeImageCropPlugin", e);
    }
  }
}
