// GENERATED by `dn create` — regenerated whenever the DartNative plugin
// dependencies in pubspec.yaml change. Single entry point:
//
//   void main() {
//     DartNativePluginRegistrant.registerAll();
//     runApp(const MyApp());
//   }
import 'dart:io' show Platform;

import 'package:dartnative/dartnative.dart';
import 'package:dartnative_ios/dartnative_ios.dart';
import 'package:dartnative_android/dartnative_android.dart';

abstract final class DartNativePluginRegistrant {
  /// Registers the platform bindings (iOS or Android). Call once at the top
  /// of `main()`, before [runApp].
  static void registerAll() {
    registerNativeBindings(
      Platform.isAndroid
          ? AndroidNativeBindings.instance
          : IOSNativeBindings.instance,
    );
  }
}
