package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.dartnative.DartNativeAndroidPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_android, com.dartnative.DartNativeAndroidPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.audio.DartNativeAudioPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_audio, com.dartnative.audio.DartNativeAudioPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.camera.DartNativeCameraPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_camera, com.dartnative.camera.DartNativeCameraPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.compressor.DartNativeCompressorPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_compressor, com.dartnative.compressor.DartNativeCompressorPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.connectivity.DartNativeConnectivityPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_connectivity, com.dartnative.connectivity.DartNativeConnectivityPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.firebase.DartNativeFirebasePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_firebase, com.dartnative.firebase.DartNativeFirebasePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.imagecrop.DartNativeImageCropPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_image_crop, com.dartnative.imagecrop.DartNativeImageCropPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.lottie.DartNativeLottiePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_lottie, com.dartnative.lottie.DartNativeLottiePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.media_picker.DartNativeMediaPickerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_media_picker, com.dartnative.media_picker.DartNativeMediaPickerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.notifications.DartNativeNotificationsPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_notifications, com.dartnative.notifications.DartNativeNotificationsPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.onnxruntime.DartNativeOnnxruntimePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_onnxruntime, com.dartnative.onnxruntime.DartNativeOnnxruntimePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.pathprovider.DartNativePathProviderPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_path_provider, com.dartnative.pathprovider.DartNativePathProviderPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.permissions.DartNativePermissionsPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_permissions, com.dartnative.permissions.DartNativePermissionsPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.securestorage.DartNativeSecureStoragePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_secure_storage, com.dartnative.securestorage.DartNativeSecureStoragePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.sharedpreferences.DartNativeSharedPreferencesPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_shared_preferences, com.dartnative.sharedpreferences.DartNativeSharedPreferencesPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.social.DartNativeSocialSignInPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_social_sign_in, com.dartnative.social.DartNativeSocialSignInPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.system.DartNativeSystemPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_system, com.dartnative.system.DartNativeSystemPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.video_player.DartNativeVideoPlayerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_video_player, com.dartnative.video_player.DartNativeVideoPlayerPlugin", e);
    }
  }
}
