#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "DN_ROOT=/Users/iosemagno/Development/zero"
export "FLUTTER_ROOT=/Users/iosemagno/Development/zero"
export "DN_APPLICATION_PATH=/Users/iosemagno/Development/dartnative/tutorials/notifications"
export "FLUTTER_APPLICATION_PATH=/Users/iosemagno/Development/dartnative/tutorials/notifications"
export "DN_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/iosemagno/Development/dartnative/tutorials/notifications/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/iosemagno/Development/dartnative/tutorials/notifications/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "DN_TARGET=lib/main.dart"
export "FLUTTER_TARGET=lib/main.dart"
export "DN_BUILD_DIR=build"
export "FLUTTER_BUILD_DIR=build"
export "DN_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NAME=1.0.0"
export "DN_BUILD_NUMBER=1.0.0"
export "FLUTTER_BUILD_NUMBER=1.0.0"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.dart_tool/package_config.json"
