package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.dartnative.DartNativeAndroidPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_android, com.dartnative.DartNativeAndroidPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.background.DartNativeBackgroundPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_background, com.dartnative.background.DartNativeBackgroundPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.notifications.DartNativeNotificationsPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_notifications, com.dartnative.notifications.DartNativeNotificationsPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.dartnative.pathprovider.DartNativePathProviderPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin dartnative_path_provider, com.dartnative.pathprovider.DartNativePathProviderPlugin", e);
    }
  }
}
